### ISSUE TITLE
Brotli

### ISSUE THREAD

**Issue by StefH** [coco-hkk/compress-action#2]
Can you please add Brotli compression?

**Comment by coco-hkk** [comment]
FYI,

refer .github/workflows/main.yml

## compress

```
- name: Compress tex with brotli
        uses: ./
        id: step4
        with:
          file-suffix: 'tex'
          target-directory-path: 'test'
          compress-tool: 'brotli'
```

## decompress

```
- name: Install brotli
       run: |
          sudo apt-get install brotli

- name: decompress
       run: |
          if [ "0"x != "${{ steps.step4.outputs.state }}"x ]; then
            echo "archive create failed, exit"
          else
            archive=${{ steps.step4.outputs.archive }}
            sudo brotli -d $archive
            tar -xvf ${archive%.*}
          fi
```
